### ISSUE TITLE
[JOSS] Example dataset generator Jupyter Notebook

### ISSUE THREAD

**Issue by abhishektiwari** [VegeWaterDynamics/motrainer#119]
At multiple places documentation suggest that 

> The example dataset ./example1_data.zarr/ can be generated using this [Jupyter Notebook](https://vegewaterdynamics.github.io/motrainer/notebooks/example_daskml/).

I was unable to find the code snippet or script to generate example dataset. 

[JOSS Review](https://github.com/openjournals/joss-reviews/issues/6591)

**Comment by rogerkuou** [comment]
Hi @abhishektiwari, the issue is stressed in PR #121. The link in the documentation page is updated.
