### ISSUE TITLE
Example Notebooks for data aligining

### ISSUE THREAD

**Issue by rogerkuou** [VegeWaterDynamics/motrainer#68]
Create example notebooks converting data sources to Dataset with aligned time and space axis.

- Example data 1: one pickle file with nested fields
    - [link](https://github.com/VegeWaterDynamics/motrainer/blob/generalization/example/example_data/example_data.pickle)
    - [example script for reading](https://github.com/VegeWaterDynamics/motrainer/blob/generalization/example/demo_jackknife.py)
- Example data 2: multiple pickle file of different attributes
    - [link](https://github.com/VegeWaterDynamics/motrainer/tree/generalization/example/dssat_s1/data)
    - [example script for reading](https://github.com/VegeWaterDynamics/motrainer/blob/generalization/example/dssat_s1/dask_ml.ipynb)

**Comment by SarahAlidoost** [comment]
@rogerkuou can you please explain the data source and license of the data? we can add them as metadata to the dataset.
