### ISSUE TITLE
pandas downgrade to <=2.0.3

### ISSUE THREAD

**Issue by cpranav93** [VegeWaterDynamics/motrainer#79]
pandas read_pickle function causes an error:
 
File "/home/cpranav93/miniconda3/envs/motrainer/lib/python3.11/site-packages/pandas/compat/pickle_compat.py", line 55, in load_reduce
    elif args and issubclass(args[0], PeriodArray):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class

SOLUTION:
Downgrade pandas to 2.0.3.

**Comment by SarahAlidoost** [comment]
see #76

**Comment by cpranav93** [comment]
Thanks Sarah! We should commit this to the main repo and the generalization repo. @rogerkuou, thoughts?

**Comment by rogerkuou** [comment]
fixed by #86
