### ISSUE TITLE
np.int deprecated

### ISSUE THREAD

**Issue by cpranav93** [VegeWaterDynamics/motrainer#80]
np.int raises an error from numpy 1.24 onwards and this is used in skopt package and has not been addressed yet. 

Therefore numpy needs to be downgraded to <1.24 for this to raise a warning instead of an error

**Comment by SarahAlidoost** [comment]
if we downgrade `numpy <1.2.0`, pandas cannot be installed, see [pandas dependencies](https://github.com/pandas-dev/pandas/blob/0f437949513225922d851e9581723d82120684a6/pyproject.toml#L25).

**Comment by SarahAlidoost** [comment]
Looking at the source code where scikit-optimize is used, I suggest replace scikit-optimize with alternatives.

**Comment by rogerkuou** [comment]
fixed by #86
